

export const NEW_COURSE_REQUEST = "NEW_COURSE_REQUEST";
export const NEW_COURSE_SUCCESS = "NEW_COURSE_SUCCESS";
export const NEW_COURSE_RESET = "NEW_COURSE_RESET";
export const NEW_COURSE_FAIL = "COURSE_FAIL";
export const ADMIN_COURSE_REQUEST = "ADMIN_COURSE_REQUEST";
export const ADMIN_COURSE_SUCCESS = "ADMIN_COURSE_SUCCESS";
export const ADMIN_COURSE_FAIL = "ADMIN_COURSE_FAIL";
export const ALL_COURSE_REQUEST = "ALL_COURSE_REQUEST";
export const ALL_COURSE_SUCCESS = "ALL_COURSE_SUCCESS";
export const ALL_COURSE_FAIL = "ALL_COURSE_FAIL";

// export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
// export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
// export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";




// export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
// export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
// export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
// export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

// export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
// export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
// export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
// export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";




export const CLEAR_ERRORS = "CLEAR_ERRORS";
